apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: example-api
  description: API consumed by the example frontend component.
spec:
  type: openapi
  lifecycle: production
  owner: eagles
  definition: |
    openapi: 3.0.0
    info:
      title: Example API
      version: 1.0.0
    paths:
      /example:
        get:
          summary: Example endpoint
          responses:
            '200':
              description: OK