---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-frontend
  description: This is an example frontend component.
  tags:
    - frontend
    - example
  annotations:
    backstage.io/techdocs-entity: component:default/Github-Tutorial
spec:
  type: website
  lifecycle: production
  owner: group:default/eagles
  system: example-system
  consumesApis:
    - example-api

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petstore
  annotations:
    pagerduty.com/service-id: P3IKHYN #testing purpose only
  # This is an extra long description with Markdown
  description: |
    [The Petstore](http://petstore.example.com) is an example API used to show features of the OpenAPI spec.
    - First item
    - Second item
  links:
    - url: https://github.com/swagger-api/swagger-petstore
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: group:default/eagles
  providesApis:
    - petstore
    - streetlights

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: playback-sdk
  description: Audio and video playback SDK
spec:
  type: library
  lifecycle: experimental
  owner: group:default/eagles
  system: audio-playback

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-search
  description: Search of the wayback machine
spec:
  type: service
  lifecycle: production
  owner: group:default/eagles
  providesApis:
    - wayback-search
  consumesApis:
    - wayback-archive

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive-storage
  description: Storage subsystem of the Wayback Archive
spec:
  type: service
  lifecycle: production
  owner: group:default/eagles
  subcomponentOf: wayback-archive

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive
  description: Archive of the wayback machine
spec:
  type: service
  lifecycle: production
  owner: group:default/eagles
  providesApis:
    - wayback-archive

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: wayback-archive-ingestion
  description: Ingestion subsystem of the Wayback Archive
spec:
  type: service
  lifecycle: production
  owner: group:default/eagles
  subcomponentOf: wayback-archive

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: queue-proxy
  description: Queue Proxy
  tags:
    - go
    - website
spec:
  type: website
  lifecycle: production
  owner: group:default/eagles
  system: podcast
