---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: artists
  description: Everything related to artists
  title: Artists
  links:
    - url: http://example.com/domain/artists/
      title: Domain Readme
    - url: http://example.com/domains/artists/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: group:default/eagles
  subdomainOf: audio

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: audio
  description: Everything related to audio
  links:
    - url: http://example.com/domain/audio/
      title: Domain Readme
    - url: http://example.com/domains/audio/dashboard
      title: Domain Metrics Dashboard
      icon: dashboard
spec:
  owner: group:default/eagles

---
apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: playback
  description: Everything related to audio playback
spec:
  owner: group:default/eagles
  subdomainOf: audio